<?php // Code generated by gen:dao CLI tool. DO NOT EDIT.

declare(strict_types=1);

namespace app\model;

use think\Model;

class Setting extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $name = 'setting';

    /**
     * The primary key associated with the table.
     *
     * @var string
     */
    protected $pk = 'id';
}