<?php // Code generated by gen:dao CLI tool. DO NOT EDIT.

declare(strict_types=1);

namespace app\entity;

class ContentEntity
{

    /**
     * @var int 
     */
    public int $id;

    /**
     * @var int 父级的ID
     */
    public int $parent_id;

    /**
     * @var int 内容类型:1站内,2站外
     */
    public int $in_station;

    /**
     * @var int 模型ID
     */
    public int $pattern_id;

    /**
     * @var string 模型类型
     */
    public string $pattern_code;

    /**
     * @var string 标题
     */
    public string $title;

    /**
     * @var string 关键词
     */
    public string $keywords;

    /**
     * @var string 描述
     */
    public string $description;

    /**
     * @var string 编辑人员
     */
    public string $author;

    /**
     * @var string 图片
     */
    public string $image;

    /**
     * @var string 简介
     */
    public string $intro;

    /**
     * @var string 描述
     */
    public string $content;

    /**
     * @var string JSON内容扩展
     */
    public string $extension;

    /**
     * @var string 附件
     */
    public string $attachment;

    /**
     * @var string 站外链接
     */
    public string $redirect_url;

    /**
     * @var string 频道模板
     */
    public string $template_index;

    /**
     * @var string 列表模板
     */
    public string $template_list;

    /**
     * @var string 详情模板
     */
    public string $template_detail;

    /**
     * @var int 排序
     */
    public int $sort;

    /**
     * @var int 状态:1正常,2禁用
     */
    public int $status;

    /**
     * @var \DateTime 
     */
    public \DateTime $create_time;

    /**
     * @var \DateTime 
     */
    public \DateTime $update_time;

    /**
     * @var \DateTime 
     */
    public \DateTime $delete_time;

    /**
     * 获取
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * 设置
     * @param int $value
     */
    public function setId(int $value): void
    {
        $this->id = $value;
    }

    /**
     * 获取父级的ID
     * @return int
     */
    public function getParentId(): int
    {
        return $this->parent_id;
    }

    /**
     * 设置父级的ID
     * @param int $value
     */
    public function setParentId(int $value): void
    {
        $this->parent_id = $value;
    }

    /**
     * 获取内容类型:1站内,2站外
     * @return int
     */
    public function getInStation(): int
    {
        return $this->in_station;
    }

    /**
     * 设置内容类型:1站内,2站外
     * @param int $value
     */
    public function setInStation(int $value): void
    {
        $this->in_station = $value;
    }

    /**
     * 获取模型ID
     * @return int
     */
    public function getPatternId(): int
    {
        return $this->pattern_id;
    }

    /**
     * 设置模型ID
     * @param int $value
     */
    public function setPatternId(int $value): void
    {
        $this->pattern_id = $value;
    }

    /**
     * 获取模型类型
     * @return string
     */
    public function getPatternCode(): string
    {
        return $this->pattern_code;
    }

    /**
     * 设置模型类型
     * @param string $value
     */
    public function setPatternCode(string $value): void
    {
        $this->pattern_code = $value;
    }

    /**
     * 获取标题
     * @return string
     */
    public function getTitle(): string
    {
        return $this->title;
    }

    /**
     * 设置标题
     * @param string $value
     */
    public function setTitle(string $value): void
    {
        $this->title = $value;
    }

    /**
     * 获取关键词
     * @return string
     */
    public function getKeywords(): string
    {
        return $this->keywords;
    }

    /**
     * 设置关键词
     * @param string $value
     */
    public function setKeywords(string $value): void
    {
        $this->keywords = $value;
    }

    /**
     * 获取描述
     * @return string
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * 设置描述
     * @param string $value
     */
    public function setDescription(string $value): void
    {
        $this->description = $value;
    }

    /**
     * 获取编辑人员
     * @return string
     */
    public function getAuthor(): string
    {
        return $this->author;
    }

    /**
     * 设置编辑人员
     * @param string $value
     */
    public function setAuthor(string $value): void
    {
        $this->author = $value;
    }

    /**
     * 获取图片
     * @return string
     */
    public function getImage(): string
    {
        return $this->image;
    }

    /**
     * 设置图片
     * @param string $value
     */
    public function setImage(string $value): void
    {
        $this->image = $value;
    }

    /**
     * 获取简介
     * @return string
     */
    public function getIntro(): string
    {
        return $this->intro;
    }

    /**
     * 设置简介
     * @param string $value
     */
    public function setIntro(string $value): void
    {
        $this->intro = $value;
    }

    /**
     * 获取描述
     * @return string
     */
    public function getContent(): string
    {
        return $this->content;
    }

    /**
     * 设置描述
     * @param string $value
     */
    public function setContent(string $value): void
    {
        $this->content = $value;
    }

    /**
     * 获取JSON内容扩展
     * @return string
     */
    public function getExtension(): string
    {
        return $this->extension;
    }

    /**
     * 设置JSON内容扩展
     * @param string $value
     */
    public function setExtension(string $value): void
    {
        $this->extension = $value;
    }

    /**
     * 获取附件
     * @return string
     */
    public function getAttachment(): string
    {
        return $this->attachment;
    }

    /**
     * 设置附件
     * @param string $value
     */
    public function setAttachment(string $value): void
    {
        $this->attachment = $value;
    }

    /**
     * 获取站外链接
     * @return string
     */
    public function getRedirectUrl(): string
    {
        return $this->redirect_url;
    }

    /**
     * 设置站外链接
     * @param string $value
     */
    public function setRedirectUrl(string $value): void
    {
        $this->redirect_url = $value;
    }

    /**
     * 获取频道模板
     * @return string
     */
    public function getTemplateIndex(): string
    {
        return $this->template_index;
    }

    /**
     * 设置频道模板
     * @param string $value
     */
    public function setTemplateIndex(string $value): void
    {
        $this->template_index = $value;
    }

    /**
     * 获取列表模板
     * @return string
     */
    public function getTemplateList(): string
    {
        return $this->template_list;
    }

    /**
     * 设置列表模板
     * @param string $value
     */
    public function setTemplateList(string $value): void
    {
        $this->template_list = $value;
    }

    /**
     * 获取详情模板
     * @return string
     */
    public function getTemplateDetail(): string
    {
        return $this->template_detail;
    }

    /**
     * 设置详情模板
     * @param string $value
     */
    public function setTemplateDetail(string $value): void
    {
        $this->template_detail = $value;
    }

    /**
     * 获取排序
     * @return int
     */
    public function getSort(): int
    {
        return $this->sort;
    }

    /**
     * 设置排序
     * @param int $value
     */
    public function setSort(int $value): void
    {
        $this->sort = $value;
    }

    /**
     * 获取状态:1正常,2禁用
     * @return int
     */
    public function getStatus(): int
    {
        return $this->status;
    }

    /**
     * 设置状态:1正常,2禁用
     * @param int $value
     */
    public function setStatus(int $value): void
    {
        $this->status = $value;
    }

    /**
     * 获取
     * @return \DateTime
     */
    public function getCreateTime(): \DateTime
    {
        return $this->create_time;
    }

    /**
     * 设置
     * @param \DateTime $value
     */
    public function setCreateTime(\DateTime $value): void
    {
        $this->create_time = $value;
    }

    /**
     * 获取
     * @return \DateTime
     */
    public function getUpdateTime(): \DateTime
    {
        return $this->update_time;
    }

    /**
     * 设置
     * @param \DateTime $value
     */
    public function setUpdateTime(\DateTime $value): void
    {
        $this->update_time = $value;
    }

    /**
     * 获取
     * @return \DateTime
     */
    public function getDeleteTime(): \DateTime
    {
        return $this->delete_time;
    }

    /**
     * 设置
     * @param \DateTime $value
     */
    public function setDeleteTime(\DateTime $value): void
    {
        $this->delete_time = $value;
    }

}