<?php // Code generated by gen:dao CLI tool. DO NOT EDIT.

declare(strict_types=1);

namespace app\entity;

class NavEntity
{

    /**
     * @var int 
     */
    public int $id;

    /**
     * @var int 父级ID
     */
    public int $parent_id;

    /**
     * @var enum 导航类型
     */
    public enum $type;

    /**
     * @var string 导航文字
     */
    public string $name;

    /**
     * @var string 导航描述
     */
    public string $description;

    /**
     * @var string 小图标
     */
    public string $icon;

    /**
     * @var string 链接地址
     */
    public string $link;

    /**
     * @var enum 打开方式
     */
    public enum $target;

    /**
     * @var int 排序
     */
    public int $sort;

    /**
     * @var int 状态:1正常,2禁用
     */
    public int $status;

    /**
     * @var \DateTime 
     */
    public \DateTime $create_time;

    /**
     * @var \DateTime 
     */
    public \DateTime $update_time;

    /**
     * 获取
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * 设置
     * @param int $value
     */
    public function setId(int $value): void
    {
        $this->id = $value;
    }

    /**
     * 获取父级ID
     * @return int
     */
    public function getParentId(): int
    {
        return $this->parent_id;
    }

    /**
     * 设置父级ID
     * @param int $value
     */
    public function setParentId(int $value): void
    {
        $this->parent_id = $value;
    }

    /**
     * 获取导航类型
     * @return enum
     */
    public function getType(): enum
    {
        return $this->type;
    }

    /**
     * 设置导航类型
     * @param enum $value
     */
    public function setType(enum $value): void
    {
        $this->type = $value;
    }

    /**
     * 获取导航文字
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * 设置导航文字
     * @param string $value
     */
    public function setName(string $value): void
    {
        $this->name = $value;
    }

    /**
     * 获取导航描述
     * @return string
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * 设置导航描述
     * @param string $value
     */
    public function setDescription(string $value): void
    {
        $this->description = $value;
    }

    /**
     * 获取小图标
     * @return string
     */
    public function getIcon(): string
    {
        return $this->icon;
    }

    /**
     * 设置小图标
     * @param string $value
     */
    public function setIcon(string $value): void
    {
        $this->icon = $value;
    }

    /**
     * 获取链接地址
     * @return string
     */
    public function getLink(): string
    {
        return $this->link;
    }

    /**
     * 设置链接地址
     * @param string $value
     */
    public function setLink(string $value): void
    {
        $this->link = $value;
    }

    /**
     * 获取打开方式
     * @return enum
     */
    public function getTarget(): enum
    {
        return $this->target;
    }

    /**
     * 设置打开方式
     * @param enum $value
     */
    public function setTarget(enum $value): void
    {
        $this->target = $value;
    }

    /**
     * 获取排序
     * @return int
     */
    public function getSort(): int
    {
        return $this->sort;
    }

    /**
     * 设置排序
     * @param int $value
     */
    public function setSort(int $value): void
    {
        $this->sort = $value;
    }

    /**
     * 获取状态:1正常,2禁用
     * @return int
     */
    public function getStatus(): int
    {
        return $this->status;
    }

    /**
     * 设置状态:1正常,2禁用
     * @param int $value
     */
    public function setStatus(int $value): void
    {
        $this->status = $value;
    }

    /**
     * 获取
     * @return \DateTime
     */
    public function getCreateTime(): \DateTime
    {
        return $this->create_time;
    }

    /**
     * 设置
     * @param \DateTime $value
     */
    public function setCreateTime(\DateTime $value): void
    {
        $this->create_time = $value;
    }

    /**
     * 获取
     * @return \DateTime
     */
    public function getUpdateTime(): \DateTime
    {
        return $this->update_time;
    }

    /**
     * 设置
     * @param \DateTime $value
     */
    public function setUpdateTime(\DateTime $value): void
    {
        $this->update_time = $value;
    }

}