<?php // Code generated by gen:dao CLI tool. DO NOT EDIT.

declare(strict_types=1);

namespace app\entity;

class PatternEntity
{

    /**
     * @var string 模型编码
     */
    public string $code;

    /**
     * @var \DateTime 
     */
    public \DateTime $create_time;

    /**
     * @var \DateTime 
     */
    public \DateTime $delete_time;

    /**
     * @var string 模型附加字段
     */
    public string $fields;

    /**
     * @var int 
     */
    public int $id;

    /**
     * @var string 模型描述
     */
    public string $intro;

    /**
     * @var string 模型名称
     */
    public string $name;

    /**
     * @var int 状态:1正常，2不正常
     */
    public int $status;

    /**
     * @var int 系统模型:1是，2否
     */
    public int $system;

    /**
     * @var \DateTime 
     */
    public \DateTime $update_time;

    /**
     * 获取模型编码
     */
    public function getCode(): string
    {
        return $this->code;
    }

    /**
     * 设置模型编码
     */
    public function setCode(string $value): void
    {
        $this->code = $value;
    }

    /**
     * 获取
     */
    public function getCreateTime(): \DateTime
    {
        return $this->create_time;
    }

    /**
     * 设置
     */
    public function setCreateTime(\DateTime $value): void
    {
        $this->create_time = $value;
    }

    /**
     * 获取
     */
    public function getDeleteTime(): \DateTime
    {
        return $this->delete_time;
    }

    /**
     * 设置
     */
    public function setDeleteTime(\DateTime $value): void
    {
        $this->delete_time = $value;
    }

    /**
     * 获取模型附加字段
     */
    public function getFields(): string
    {
        return $this->fields;
    }

    /**
     * 设置模型附加字段
     */
    public function setFields(string $value): void
    {
        $this->fields = $value;
    }

    /**
     * 获取
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * 设置
     */
    public function setId(int $value): void
    {
        $this->id = $value;
    }

    /**
     * 获取模型描述
     */
    public function getIntro(): string
    {
        return $this->intro;
    }

    /**
     * 设置模型描述
     */
    public function setIntro(string $value): void
    {
        $this->intro = $value;
    }

    /**
     * 获取模型名称
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * 设置模型名称
     */
    public function setName(string $value): void
    {
        $this->name = $value;
    }

    /**
     * 获取状态:1正常，2不正常
     */
    public function getStatus(): int
    {
        return $this->status;
    }

    /**
     * 设置状态:1正常，2不正常
     */
    public function setStatus(int $value): void
    {
        $this->status = $value;
    }

    /**
     * 获取系统模型:1是，2否
     */
    public function getSystem(): int
    {
        return $this->system;
    }

    /**
     * 设置系统模型:1是，2否
     */
    public function setSystem(int $value): void
    {
        $this->system = $value;
    }

    /**
     * 获取
     */
    public function getUpdateTime(): \DateTime
    {
        return $this->update_time;
    }

    /**
     * 设置
     */
    public function setUpdateTime(\DateTime $value): void
    {
        $this->update_time = $value;
    }

}