<?php // Code generated by gen:dao CLI tool. DO NOT EDIT.

declare(strict_types=1);

namespace app\entity;

class PermissionEntity
{

    /**
     * @var string 
     */
    public string $create_time;

    /**
     * @var string 
     */
    public string $delete_time;

    /**
     * @var string ICON图标
     */
    public string $icon;

    /**
     * @var int 
     */
    public int $id;

    /**
     * @var int 是否为管理菜单：1是,2否
     */
    public int $is_menu;

    /**
     * @var string 规则名称
     */
    public string $name;

    /**
     * @var int 父级ID
     */
    public int $parent_id;

    /**
     * @var string 规则标识
     */
    public string $rule;

    /**
     * @var int 排序
     */
    public int $sort;

    /**
     * @var int 状态:1正常,2禁用
     */
    public int $status;

    /**
     * @var string 
     */
    public string $update_time;

    /**
     * 获取
     */
    public function getCreateTime(): string
    {
        return $this->create_time;
    }

    /**
     * 设置
     */
    public function setCreateTime(string $value): void
    {
        $this->create_time = $value;
    }

    /**
     * 获取
     */
    public function getDeleteTime(): string
    {
        return $this->delete_time;
    }

    /**
     * 设置
     */
    public function setDeleteTime(string $value): void
    {
        $this->delete_time = $value;
    }

    /**
     * 获取ICON图标
     */
    public function getIcon(): string
    {
        return $this->icon;
    }

    /**
     * 设置ICON图标
     */
    public function setIcon(string $value): void
    {
        $this->icon = $value;
    }

    /**
     * 获取
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * 设置
     */
    public function setId(int $value): void
    {
        $this->id = $value;
    }

    /**
     * 获取是否为管理菜单：1是,2否
     */
    public function getIsMenu(): int
    {
        return $this->is_menu;
    }

    /**
     * 设置是否为管理菜单：1是,2否
     */
    public function setIsMenu(int $value): void
    {
        $this->is_menu = $value;
    }

    /**
     * 获取规则名称
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * 设置规则名称
     */
    public function setName(string $value): void
    {
        $this->name = $value;
    }

    /**
     * 获取父级ID
     */
    public function getParentId(): int
    {
        return $this->parent_id;
    }

    /**
     * 设置父级ID
     */
    public function setParentId(int $value): void
    {
        $this->parent_id = $value;
    }

    /**
     * 获取规则标识
     */
    public function getRule(): string
    {
        return $this->rule;
    }

    /**
     * 设置规则标识
     */
    public function setRule(string $value): void
    {
        $this->rule = $value;
    }

    /**
     * 获取排序
     */
    public function getSort(): int
    {
        return $this->sort;
    }

    /**
     * 设置排序
     */
    public function setSort(int $value): void
    {
        $this->sort = $value;
    }

    /**
     * 获取状态:1正常,2禁用
     */
    public function getStatus(): int
    {
        return $this->status;
    }

    /**
     * 设置状态:1正常,2禁用
     */
    public function setStatus(int $value): void
    {
        $this->status = $value;
    }

    /**
     * 获取
     */
    public function getUpdateTime(): string
    {
        return $this->update_time;
    }

    /**
     * 设置
     */
    public function setUpdateTime(string $value): void
    {
        $this->update_time = $value;
    }

}