<?php // Code generated by gen:dao CLI tool. DO NOT EDIT.

declare(strict_types=1);

namespace app\entity;

class SettingEntity
{

    /**
     * @var string 配置code
     */
    public string $code;

    /**
     * @var int 
     */
    public int $id;

    /**
     * @var string 配置名称
     */
    public string $name;

    /**
     * @var int 父节点id
     */
    public int $parent_id;

    /**
     * @var string 配置数组索引
     */
    public string $range;

    /**
     * @var int 排序
     */
    public int $sort;

    /**
     * @var string 配置类型：text、select、file、hidden等
     */
    public string $type;

    /**
     * @var string 该项配置的值
     */
    public string $value;

    /**
     * 获取配置code
     */
    public function getCode(): string
    {
        return $this->code;
    }

    /**
     * 设置配置code
     */
    public function setCode(string $value): void
    {
        $this->code = $value;
    }

    /**
     * 获取
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * 设置
     */
    public function setId(int $value): void
    {
        $this->id = $value;
    }

    /**
     * 获取配置名称
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * 设置配置名称
     */
    public function setName(string $value): void
    {
        $this->name = $value;
    }

    /**
     * 获取父节点id
     */
    public function getParentId(): int
    {
        return $this->parent_id;
    }

    /**
     * 设置父节点id
     */
    public function setParentId(int $value): void
    {
        $this->parent_id = $value;
    }

    /**
     * 获取配置数组索引
     */
    public function getRange(): string
    {
        return $this->range;
    }

    /**
     * 设置配置数组索引
     */
    public function setRange(string $value): void
    {
        $this->range = $value;
    }

    /**
     * 获取排序
     */
    public function getSort(): int
    {
        return $this->sort;
    }

    /**
     * 设置排序
     */
    public function setSort(int $value): void
    {
        $this->sort = $value;
    }

    /**
     * 获取配置类型：text、select、file、hidden等
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * 设置配置类型：text、select、file、hidden等
     */
    public function setType(string $value): void
    {
        $this->type = $value;
    }

    /**
     * 获取该项配置的值
     */
    public function getValue(): string
    {
        return $this->value;
    }

    /**
     * 设置该项配置的值
     */
    public function setValue(string $value): void
    {
        $this->value = $value;
    }

}