<?php // Code generated by gen:dao CLI tool. DO NOT EDIT.

declare(strict_types=1);

namespace app\entity;

class UserLogEntity
{

    /**
     * @var string 
     */
    public string $create_time;

    /**
     * @var int 
     */
    public int $id;

    /**
     * @var string IP地址
     */
    public string $ip_address;

    /**
     * @var string 日志级别
     */
    public string $level;

    /**
     * @var string 日志内容
     */
    public string $message;

    /**
     * @var string 
     */
    public string $update_time;

    /**
     * @var string User Agent
     */
    public string $user_agent;

    /**
     * @var int 用户ID
     */
    public int $user_id;

    /**
     * 获取
     */
    public function getCreateTime(): string
    {
        return $this->create_time;
    }

    /**
     * 设置
     */
    public function setCreateTime(string $value): void
    {
        $this->create_time = $value;
    }

    /**
     * 获取
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * 设置
     */
    public function setId(int $value): void
    {
        $this->id = $value;
    }

    /**
     * 获取IP地址
     */
    public function getIpAddress(): string
    {
        return $this->ip_address;
    }

    /**
     * 设置IP地址
     */
    public function setIpAddress(string $value): void
    {
        $this->ip_address = $value;
    }

    /**
     * 获取日志级别
     */
    public function getLevel(): string
    {
        return $this->level;
    }

    /**
     * 设置日志级别
     */
    public function setLevel(string $value): void
    {
        $this->level = $value;
    }

    /**
     * 获取日志内容
     */
    public function getMessage(): string
    {
        return $this->message;
    }

    /**
     * 设置日志内容
     */
    public function setMessage(string $value): void
    {
        $this->message = $value;
    }

    /**
     * 获取
     */
    public function getUpdateTime(): string
    {
        return $this->update_time;
    }

    /**
     * 设置
     */
    public function setUpdateTime(string $value): void
    {
        $this->update_time = $value;
    }

    /**
     * 获取User Agent
     */
    public function getUserAgent(): string
    {
        return $this->user_agent;
    }

    /**
     * 设置User Agent
     */
    public function setUserAgent(string $value): void
    {
        $this->user_agent = $value;
    }

    /**
     * 获取用户ID
     */
    public function getUserId(): int
    {
        return $this->user_id;
    }

    /**
     * 设置用户ID
     */
    public function setUserId(int $value): void
    {
        $this->user_id = $value;
    }

}